# Control D Configuration

[listener.0]
  ip = "0.0.0.0"
  port = 53

[network.0]
  cidrs = ["0.0.0.0/0"]
  name = "Any network"

[upstream.0]
  name = "Control D DoQ"
  bootstrap_ip = "76.76.2.11"
  endpoint = "p2.freedns.controld.com"
  type = "doq"

[upstream.1]
  name = "Cloudflare DoT"
  endpoint = "1.1.1.1:853"
  type = "dot"
