version: "3.8"
name: servarr
services:
  # Networking
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    deploy:
      replicas: 2
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=/run/secrets/mullvad_private_key
      - WIREGUARD_ADDRESSES=10.70.151.218/32
      - SERVER_CITIES=Seattle WA
    secrets:
      - mullvad_private_key
    ports:
      - 8191:8191 # flaresolverr
      - 8989:8989 # sonarr
      - 7878:7878 # radarr
      - 6767:6767 # bazarr
      - 9696:9696 # prowlarr
      - 8080:8080 # qbittorrent
      - 6881:6881 # qbittorrent
      - 6881:6881/udp # qbittorrent
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: service:gluetun
    environment:
      - TZ=Canada/Pacific
    restart: unless-stopped

  # User-facing apps
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - device=/dev/dri:/dev/dri
      - PUID=13001
      - PGID=13000
      - TZ=Canada/Pacific
      - VERSION=docker
    volumes: 
      - /home/nathan/servarr/config/plex-config:/config
      - /mnt/data/media:/media
    labels:
      - docker-volume-backup.stop-during-backup=plex
    ports:
      - 32400:32400
    restart: unless-stopped
  
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=13002
      - PGID=13000
      - TZ=Canada/Pacific
    volumes:
      - /home/nathan/servarr/config/overseerr-config:/config
    labels:
      - docker-volume-backup.stop-during-backup=overseerr
    ports:
      - 5055:5055
    restart: unless-stopped

  # Media management
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: service:gluetun
    environment:
      - PUID=13003
      - PGID=13000
      - UMASK=002
      - TZ=Canada/Pacific
    volumes:
      - /home/nathan/servarr/config/sonarr-config:/config
      - /mnt/data:/data
    labels:
      - docker-volume-backup.stop-during-backup=sonarr
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:gluetun
    environment:
      - PUID=13004
      - PGID=13000
      - UMASK=002
      - TZ=Canada/Pacific
    volumes:
      - /home/nathan/servarr/config/radarr-config:/config
      - /mnt/data:/data
    labels:
      - docker-volume-backup.stop-during-backup=radarr
    restart: unless-stopped

  bazarr: 
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    network_mode: service:gluetun
    environment:
      - PUID=13005
      - PGID=13000
      - TZ=Canada/Pacific
    volumes:
      - /home/nathan/servarr/config/bazarr-config:/config
      - /mnt/data/media:/media
    labels:
      - docker-volume-backup.stop-during-backup=bazarr
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: service:gluetun
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=Canada/Pacific
    volumes:
      - /home/nathan/servarr/config/prowlarr-config:/config
    labels:
      - docker-volume-backup.stop-during-backup=prowlarr
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=Canada/Pacific
      - WEBUI_PORT=8080
    volumes:
      - /home/nathan/servarr/config/qbittorrent-config:/config
      - /mnt/data/torrents:/data/torrents
    labels:
      - docker-volume-backup.stop-during-backup=qbittorrent
    restart: unless-stopped

  # User management
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    depends_on:
      - plex
    environment:
      - PUID=1000
      - PGID=13000
      - TZ=Canada/Pacific
    volumes:
      - /home/nathan/servarr/config/tautulli-config:/config
    labels:
      - docker-volume-backup.stop-during-backup=tautulli
    ports:
      - 8181:8181
    restart: unless-stopped

  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr
    volumes:
      - /home/nathan/servarr/config/wizarr-config:/data/database
    labels:
      - docker-volume-backup.stop-during-backup=wizarr
    ports:
      - 5690:5690
    restart: unless-stopped

  # Container updates
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    command: --cleanup true --remove-volumes true --schedule "30 9 * * *" --rolling-restart true
    restart: unless-stopped
  
# Docker environment
secrets:
  mullvad_private_key:
    file: mullvad_private_key.txt