version: "3.8"
name: servarr
services:
  # cloudflare:
  #   image: cloudflare/cloudflared:latest
  #   container_name: cloudflared
  #   command: tunnel run --token <token>
  #   restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - device=/dev/dri:/dev/dri
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Pacific
      - VERSION=docker
    volumes: 
      - plex-config:/config
      - data:/data
    restart: unless-stopped
    ports:
      - 32400:32400
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Pacific
    volumes:
      - sonarr-config:/config
      - data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Pacific
    volumes:
      - radarr-config:/config
      - data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
  # gluetun:
  #   image: qmcgaw/gluetun:latest
  #   container_name: gluetun
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #     - VPN_SERVICE_PROVIDER=mullvad
  #     - VPN_TYPE=wireguard
  #     - WIREGUARD_PRIVATE_KEY=<key>
  #     - WIREGUARD_ADDRESSES=10.69.232.169/32
  #     - SERVER_CITIES=Vancouver
  # watchtower:
  #   image: containrrr/watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --interval 30
volumes:
  plex-config:
  sonarr-config:
  radarr-config:
  data:
