name: "SSH to server"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Run SSH command
    runs-on: ubuntu-latest
    steps:
    - name: connect to remote server
      uses: nathanjnorris/cloudflared-ssh-action@latest
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        commands: '/bin/bash -c "cat file.txt < input.txt"'