name: "SSH to server"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Run SSH command
    runs-on: ubuntu-latest
    steps:
    - name: connect to remote server
      uses: npgy/cloudflared-ssh-action@v2.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_SERNAME }}
        private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        commands: cd /home/nathan mkdir hello_world
