name: Pull down and compose up
on: 
  push:
    branches: 
    - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Connect to servarr
      uses: nathanjnorris/cloudflared-ssh-action@v1.0
      with:
        host: ${{ vars.HOST }}
        username: ${{ secrets.USERNAME }}
        private_key: ${{ secrets.PRIVKEY }}
        port: ${{ secrets.PORT }}
        commands: cd repo_dir; git pull; /usr/local/bin/docker compose up --build -d