on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: Run SSH command
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: ls
      run: |
          ls
    - name: connect to remote server
      uses: nathanjnorris/cloudflared-ssh-action@latest
      with:
        host: ${{ vars.SSH_HOST }}
        username: ${{ vars.SSH_USERNAME }}
        private_key_filename: ${{ vars.SSH_PRIVATE_KEY_FILENAME }}
        private_key_value: ${{ secrets.SSH_PRIVATE_KEY_VALUE }}
        port: ${{ vars.SSH_PORT }}
        service_token_id: ${{ vars.SERVICE_TOKEN_ID }}
        service_token_secret: ${{ secrets.SERVICE_TOKEN_SECRET }}
        commands: mkdir hello_world -v
