on: 
  pull_request:

permissions: read-all
jobs:
  terraform_format_and_docs:
    name: Terraform formatting and documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout coe
        uses: actions/checkout@v4
        with: 
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -recursive .
      
      - name: Terraform Docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          find-dir: .
          output-file: README.md
          output-method: inject
          git-push: true
          git-commit-message: Terraform formatting and documentation